### ISSUE TITLE
Modernize GitHub authentication

### ISSUE THREAD

**Issue by lrytz** [scala/compiler-benchq#15]
Message from GitHub

----

Hello there!

On February 13th, 2020 at 10:09 (UTC) your application (benchq) used an access token (with the User-Agent AHC/2.0) as part of a query parameter to access an endpoint through the GitHub API.

https://api.github.com/user

Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated and will be removed July 1st, 2020.

Depending on your API usage, we'll be sending you this email reminder once every 3 days.

Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.

**Comment by retronym** [comment]
The OAuth library we use has a fix in a newer version: https://github.com/mohiva/play-silhouette/pull/576#issuecomment-584031898 

That may involve us upgrading to Play 2.8.
