### ISSUE TITLE
Builds failing, maybe due to the travis-ci.com migration

### ISSUE THREAD

**Issue by retronym** [scala/compiler-benchq#17]
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/65551/108010846-9175a400-7051-11eb-9737-e77002135c5b.png">

**Comment by lrytz** [comment]
I think these are old jobs, but there's some other issue. I'll take a look.

**Comment by lrytz** [comment]
the machine (jenkins-grafana) is also running out of disk space

/dev/xvda1      7.8G  7.0G  349M  96% /

**Comment by lrytz** [comment]
Resized the disk to 16G and installed some updates. Then cleared out the task list. Things work fine now, I followed the log for the merge of https://github.com/scala/scala/pull/9500, webhooks from github, jenkins, travis are fine, results appear on grafana.

I should add some maintenance stuff, like remove "waiting" tasks after a day or so. And some bulk-delete functionality.

**Comment by retronym** [comment]
Thanks!
